exclude_paths:
  - bin
  - config
  - db
  - vendor
  - tmp
  - storage

detectors:
  IrresponsibleModule:
    enabled: false

  UncommunicativeVariableName:
    accept:
      - e
      - i
      - n
      - r
      - b
      - p
      - t
      - id

  UncommunicativeMethodName:
    enabled: true

  TooManyStatements:
    max_statements: 10
    exclude:
      - initialize

  UtilityFunction:
    public_methods_only: true

  DataClump:
    max_copies: 3
    min_clump_size: 3

  DuplicateMethodCall:
    max_calls: 2
    allow_calls:
      - puts
      - render
      - redirect_to

  NestedIterators:
    max_allowed_nesting: 2

  TooManyInstanceVariables:
    max_instance_variables: 5

  TooManyMethods:
    max_methods: 15

  LongParameterList:
    max_params: 4

  InstanceVariableAssumption:
    exclude:
      - ApiKey  # @raw_token is set in before_validation callback
      - Api::V1::BaseController  # @current_api_key set in before_action
      - Api::V1::ReconciliationsController  # @reconciliation set in before_action

  UncommunicativeModuleName:
    exclude:
      - Api::V1  # Standard API versioning convention

  MissingSafeMethod:
    exclude:
      - Api::V1::BaseController  # authenticate_api_key! is Rails before_action convention

  FeatureEnvy:
    exclude:
      - Api::V1::BaseController#extract_token_from_header  # Simple header parsing method
